name: Go build

on:
  push:
    branches:
      - main
      - feature/*
    tags:
      - "v*"

jobs:
  build:
    uses: pflege-de/github-workflows/.github/workflows/go-full-build.yml@main
    with:
      build_name: json-checker
      repo_ref: ${{ github.ref_name}}
    secrets:
      NETRC: ${{ secrets.NETRC }}
